name: 'Main Terraform Workflow'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  call-terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      auto_approve: false

  manual-approval:
    needs: call-terraform
    runs-on: ubuntu-latest
    steps:
      - name: Await Manual Approval
        run: |
          echo "Manual approval required. Approve the 'terraform-apply' job to continue."
          sleep 1h  # Sleep for a long duration; allows manual approval to be made.
        timeout-minutes: 360  # Wait up to 6 hours for manual approval.